AllCops:
  NewCops: enable
  Exclude:
    - 'storage/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'temp/**/*'
Metrics/ClassLength:
  Max: 1500

Style/Documentation:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: true

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Metrics/BlockLength:
  Enabled: true

Style/Lambda:
  EnforcedStyle: literal

Naming/VariableNumber:
  EnforcedStyle: snake_case
